### PR TITLE
gui

### PR DESCRIPTION
**Pull request by luiztauffer**
- access to nwbn_conversion GUI
- conversion function changed
- metafile changed
- README with instructions

### CODE REVIEW

**Comment by luiztauffer** [comment]
`npz_to_nwb.py` can be removed, it was replaced by `conversion_module.py`

**Comment by bendichter** [comment]
Looks great! However, I don't like the source files being entered as a list. Could you separate them out into individual input args?

**Comment by bendichter** [comment]
Also could you fix the merge conflict?

**Comment by luiztauffer** [comment]
done

**Pull request merged**
